apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-scheduler-historical-data
  namespace: hydatis-mlops
  labels:
    app: ml-scheduler
    component: data-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-scheduler-models
  namespace: hydatis-mlops
  labels:
    app: ml-scheduler
    component: model-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-scheduler-artifacts
  namespace: hydatis-mlops
  labels:
    app: ml-scheduler
    component: artifacts
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-ml-scheduler-data
  namespace: monitoring
  labels:
    app: prometheus
    component: ml-scheduler-metrics
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: longhorn