project: hydatis_ml_scheduler
registry: /data/ml_scheduler_longhorn/feast/registry.db
provider: local
online_store:
  type: redis
  connection_string: "redis://localhost:6379"
offline_store:
  type: file
repo_path: /home/jovyan/work/feature_store/feast/feature_repo