apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: hydatis-qlearning-hpo
  namespace: kubeflow
  labels:
    app: ml-scheduler
    component: qlearning-hpo
    target: 34-percent-improvement-placement
spec:
  algorithm:
    algorithmName: hyperband
    algorithmSettings:
    - name: "resource_name"
      value: "num_epochs"
    - name: "eta"
      value: "3"
    - name: "r_l"
      value: "81"  # Minimum resource allocation
    - name: "r_u"
      value: "2187"  # Maximum resource allocation
  
  objective:
    type: maximize
    objectiveMetricName: placement_improvement_score
    additionalMetricNames:
    - reward_convergence_rate
    - policy_stability_score
    - business_impact_score
    - cluster_efficiency_improvement
  
  parameters:
  - name: learning_rate
    parameterType: double
    feasibleSpace:
      min: "0.0001"
      max: "0.01"
      step: "0.0001"
    
  - name: gamma
    parameterType: double
    feasibleSpace:
      min: "0.90"
      max: "0.99"
      step: "0.01"
    
  - name: epsilon_decay
    parameterType: double
    feasibleSpace:
      min: "0.990"
      max: "0.999"
      step: "0.001"
    
  - name: batch_size
    parameterType: int
    feasibleSpace:
      min: "16"
      max: "128"
      step: "16"
    
  - name: memory_size
    parameterType: int
    feasibleSpace:
      min: "5000"
      max: "20000"
      step: "2500"
    
  - name: hidden_size
    parameterType: int
    feasibleSpace:
      min: "64"
      max: "256"
      step: "32"
    
  - name: target_update_frequency
    parameterType: int
    feasibleSpace:
      min: "100"
      max: "1000"
      step: "100"
    
  - name: reward_function_weight_efficiency
    parameterType: double
    feasibleSpace:
      min: "0.3"
      max: "0.6"
      step: "0.05"
    
  - name: reward_function_weight_balance
    parameterType: double
    feasibleSpace:
      min: "0.2"
      max: "0.4"
      step: "0.05"
    
  - name: reward_function_weight_availability
    parameterType: double
    feasibleSpace:
      min: "0.1"
      max: "0.3"
      step: "0.05"
  
  parallelTrialCount: 3
  maxTrialCount: 40
  maxFailedTrialCount: 5
  
  trialTemplate:
    primaryContainerName: qlearning-trainer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            annotations:
              sidecar.istio.io/inject: "false"
          spec:
            containers:
            - name: qlearning-trainer
              image: hydatis/ml-scheduler-qlearning-trainer:latest
              command:
              - python
              - -u
              - /app/katib_qlearning_training.py
              args:
              - --learning_rate={{.HyperParameters.learning_rate}}
              - --gamma={{.HyperParameters.gamma}}
              - --epsilon_decay={{.HyperParameters.epsilon_decay}}
              - --batch_size={{.HyperParameters.batch_size}}
              - --memory_size={{.HyperParameters.memory_size}}
              - --hidden_size={{.HyperParameters.hidden_size}}
              - --target_update_frequency={{.HyperParameters.target_update_frequency}}
              - --reward_efficiency_weight={{.HyperParameters.reward_function_weight_efficiency}}
              - --reward_balance_weight={{.HyperParameters.reward_function_weight_balance}}
              - --reward_availability_weight={{.HyperParameters.reward_function_weight_availability}}
              - --cluster_config=hydatis_6_nodes
              - --business_target=34_percent_improvement
              env:
              - name: PROMETHEUS_URL
                value: "http://prometheus-server.monitoring:9090"
              - name: MLFLOW_TRACKING_URI
                value: "http://mlflow-server.kubeflow:5000"
              - name: HYDATIS_CLUSTER_SIZE
                value: "6"
              - name: HYDATIS_CPU_TARGET
                value: "0.65"
              - name: HYDATIS_AVAILABILITY_TARGET
                value: "0.997"
              - name: KATIB_EXPERIMENT_NAME
                value: "hydatis-qlearning-hpo"
              - name: CUDA_VISIBLE_DEVICES
                value: ""  # CPU-only training
              volumeMounts:
              - name: cluster-simulation-data
                mountPath: /app/simulation_data
              - name: model-artifacts
                mountPath: /app/models
              - name: training-logs
                mountPath: /app/logs
              resources:
                requests:
                  cpu: "2"
                  memory: "4Gi"
                limits:
                  cpu: "4"
                  memory: "8Gi"
            volumes:
            - name: cluster-simulation-data
              persistentVolumeClaim:
                claimName: hydatis-simulation-data
            - name: model-artifacts
              persistentVolumeClaim:
                claimName: ml-scheduler-model-artifacts
            - name: training-logs
              persistentVolumeClaim:
                claimName: ml-scheduler-training-logs
            restartPolicy: Never
        backoffLimit: 2