apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: hydatis-xgboost-memory-optimization
  namespace: kubeflow
  labels:
    app: ml-scheduler
    component: memory-predictor-hpo
    target: memory-efficiency-optimization
spec:
  algorithm:
    algorithmName: random
    algorithmSettings:
    - name: "random_state"
      value: "42"
  
  objective:
    type: maximize
    objectiveMetricName: memory_prediction_business_score
    additionalMetricNames:
    - memory_prediction_accuracy
    - memory_utilization_optimization
    - pod_placement_efficiency
  
  parameters:
  - name: max_depth
    parameterType: int
    feasibleSpace:
      min: "3"
      max: "8"
    
  - name: learning_rate
    parameterType: double
    feasibleSpace:
      min: "0.03"
      max: "0.15"
    
  - name: n_estimators
    parameterType: int
    feasibleSpace:
      min: "150"
      max: "350"
    
  - name: subsample
    parameterType: double
    feasibleSpace:
      min: "0.8"
      max: "1.0"
    
  - name: colsample_bytree
    parameterType: double
    feasibleSpace:
      min: "0.6"
      max: "0.9"
    
  - name: gamma
    parameterType: double
    feasibleSpace:
      min: "0.0"
      max: "0.5"
  
  parallelTrialCount: 3
  maxTrialCount: 25
  maxFailedTrialCount: 3
  
  trialTemplate:
    primaryContainerName: memory-optimization-trainer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
            - name: memory-optimization-trainer
              image: hydatis/ml-scheduler-memory-trainer:latest
              command:
              - python
              - -u  
              - /app/memory_optimization_training.py
              args:
              - --max_depth={{.HyperParameters.max_depth}}
              - --learning_rate={{.HyperParameters.learning_rate}}
              - --n_estimators={{.HyperParameters.n_estimators}}
              - --subsample={{.HyperParameters.subsample}}
              - --colsample_bytree={{.HyperParameters.colsample_bytree}}
              - --gamma={{.HyperParameters.gamma}}
              - --target=memory_efficiency_optimization
              - --cluster=hydatis_6_node
              env:
              - name: PROMETHEUS_URL
                value: "http://prometheus-server.monitoring:9090"
              - name: MLFLOW_TRACKING_URI
                value: "http://mlflow-server.kubeflow:5000"
              - name: MEMORY_OPTIMIZATION_TARGET
                value: "0.86"
              - name: KATIB_EXPERIMENT_NAME
                value: "hydatis-xgboost-memory-optimization"
              volumeMounts:
              - name: cluster-data
                mountPath: /app/data
                readOnly: true
              - name: model-output
                mountPath: /app/output
              resources:
                requests:
                  cpu: "1.5"
                  memory: "3Gi"
                limits:
                  cpu: "3"
                  memory: "6Gi"
            volumes:
            - name: cluster-data
              persistentVolumeClaim:
                claimName: hydatis-cluster-data
            - name: model-output
              persistentVolumeClaim:
                claimName: ml-scheduler-model-artifacts
            restartPolicy: Never